id: ABE9CB76B
title: Toh_155-The_Question_of_the_Naga_King_Sagara_(3)-v1
type: translation
pechas:
- IC77CCE40
- I8BAAAB2B
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-18T06:19:40.66Z'
  creationid: dirk
  eft-text-id: UT22084-058-002
  eft-text-version: 2.15.4 2020
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_155-The_Question_of_the_Naga_King_Sagara_(3)-v1
alignment_to_base:
  IC77CCE40/4AA0: 9AAD
  I8BAAAB2B/05A0: 9AAD
